version : "3"

services :
  web :
    build : .
    ports : 
      - "80:5173"

    env_file : 
      - ".env"

  backend : 
    build : "backend/"
    ports :
      - "8000:8000"

    env_file:
      - "backend/.env"
    depends_on : 
      - db
  

  db : 
    image : mysql:8
    ports :
      - "3306:3306"
    env_file: 
      - "backend/.env"
    environment : 
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DBNAME}

    