name: test build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - "*"

jobs:
  
  build_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix :
        node-version : 
          - 18
          - 20
        os: 
          - ubuntu-latest
          - windows-latest
    

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: install node
        run: npm install


      - name: build
        run: npm run build
  
  