name: test build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - "*"

jobs:
  
  build_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix :
        node-version : 
          - 18
          - 20
        os: 
          - ubuntu-latest
          - windows-latest
    

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: install node
        run: npm install


      - name: build
        run: npm run build


  backend_test:
    runs-on : ${{ matrix.os }}

    environment : "docker-compose"

    needs : 
      - build_test

    strategy :
      fail-fast : false
      matrix : 
        os : 
          - ubuntu-latest

        python-version : 
          - '3.11'
          - '3.10'

    steps : 

      - name : checkout to repo
        uses: actions/checkout@v2

      - name : setup python
        uses : actions/setup-python@v4
        with : 
          python-version : ${{ matrix.python-version }}

      - name : install deps
        working-directory : ./backend
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name : runs test
        working-directory : ./backend
        run : python manage.py test
  
  