name: test build

on:
  push:
    branches:
      - master

jobs:
  
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix :
        node-version : [18]
    

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: install node
        run: npm install


      - name: build
        run: npm run build